name: 'dimensions'
version: '1.0.0'
config-version: 2

profile: 'dimensions'

model-paths: ["models"]


target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dimensions:
    dim:
      +materialized: view
