
name: 'bookings'
version: '1.0.0'
config-version: 2

profile: 'bookings'

model-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  bookings:
    example:
      +materialized: view
