
version: 2

models:
  - name: users
    description: "The dimension model for the users"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: user_name
        description: "The user name"
        tests:
          - not_null
      - name: user_status
        description: "The status of the user"
        tests:
          - accepted_values:
              values: ['ENABLED', 'DISABLED']

  - name: projects
    description: "The dimension model for the projects"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: project_name
        description: "The project name"
        tests:
          - not_null
      - name: project_status
        description: "The status of the project"
        tests:
          - accepted_values:
              values: ['ENABLED', 'DISABLED']

