version: 2

models:
  - name: users
    description: "The dimension model for the users"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: user_name
        description: "The user name"
        tests:
          - not_null
      - name: user_status
        description: "The status of the user"
        tests:
          - accepted_values:
              values: ["ENABLED", "DISABLED"]

  - name: companies
    description: "The dimension model for the companies"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: company_name
        description: "The company name"
        tests:
          - not_null
      - name: company_status
        description: "The status of the company in the platform"
        tests:
          - accepted_values:
              values: ["ENABLED", "DISABLED"]
