name: Deploy to S3

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_S3_CI_AIRFLOW_BUCKET_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_S3_CI_AIRFLOW_BUCKET_SECRET_KEY }}
        aws-region: sa-east-1

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync . s3://ci-airflow-dags